== The CDI server application
:icons: font
:rootdir: ../../../..
:srcdir: {rootdir}/server-cdi/src

The server application is basically a simple CDI application exposing one Hello World bean.

The necessary configuration for GraniteDS is very simple and consists in adding an annotated configuration class to trigger
the startup of GraniteDS and the CDI integration (using a Servlet 3 container initializer behind the scenes):

[source,java,indent=0]
.main/java/org/graniteds/tutorial/remoting/server/HelloWorldApplication.java
----
include::{srcdir}/main/java/org/graniteds/tutorial/remoting/server/HelloWorldApplication.java[tags=server-filter]
----

Next we have to enable CDI bean scanning by adding an empty +beans.xml+ file in the +META-INF+ folder.

The actual application comprises a simple CDI named bean which we annotate with +@RemoteDestination+ to enable remote access
and with +@Named+ so it can be found by its name from the client application (see client usage <<client.destination,here>>):

[source,java,indent=0]
.main/java/org/graniteds/tutorial/remoting/server/HelloWorldServiceImpl.java
----
include::{srcdir}/main/java/org/graniteds/tutorial/remoting/server/HelloWorldService.java[tags=remote-destination]
----

Finally, here are the maven dependencies for the CDI module:
[source,xml,indent=0]
----
include::https://raw.githubusercontent.com/graniteds-tutorials/graniteds-tutorial/master/server-base/server-cdi/pom.xml[tags=maven-deps]
----
